server:
  port: 9001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com:
      netflix:
        eureka: false
        discovery: false
spring:
  application:
    name: data-service
  cloud:
    config:
      server:
        health:
          enabled: false
        git:
          uri: https://github.com/thakkarnirav123/cloud-core.git
      discovery:
        enabled: true
        


###
#   Database Settings
###
  datasource:
    username: sa
    platform: h2
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true